name: spectra_software
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyqt=5.*
  - matplotlib
  - pandas
  - pip
  - pip:
    - numpy
    - scipy
    - hitran-api
    - hitran-api2
    - lmfit
    - PyQt5
    - allantools