import time
import warnings
import os
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib as mpl
import pldspectrapy.td_support
from pldspectrapy import misc_tools, fit_data

#######################################################
#   Suppress UserWarning generated by fitting
#######################################################
warnings.filterwarnings("ignore", category=UserWarning)
#######################################################

#######################################################
#   Plot formatting
#######################################################
mpl.rcParams["backend"] = "TkAgg"
mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["ps.fonttype"] = 42
mpl.rcParams["font.family"] = "Arial"
plt.rcParams.update({"figure.autolayout": True, "lines.linewidth": 0.65})
plt.rcParams.update({"mathtext.default": "regular"})
#######################################################

start_time = time.time()

# File paths
directory_path = r"C:\Users\nicog\OneDrive\Desktop\data for graphing\stuff_for _data_fitting"
lookup_table_path = r"src/methane_absorption_multiple_conditions.csv"
file_list = glob.glob(os.path.join(directory_path, "*.cor"))

# Load the CSV lookup table
if os.path.exists(lookup_table_path):
    lookup_table = pd.read_csv(lookup_table_path)
else:
    raise FileNotFoundError("Lookup table CSV file not found.")

# Helper function to retrieve spectral data from the lookup table
def get_spectral_data_from_csv(lookup_table, temperature, mole_fraction, x_wvn):
    """
    Retrieve spectral data from CSV lookup table.

    Parameters
    ----------
    lookup_table : pd.DataFrame
        DataFrame containing the lookup table.
    temperature : float
        Temperature in K.
    mole_fraction : float
        Mole fraction of the gas.
    x_wvn : numpy array
        Wavenumber array.

    Returns
    -------
    spectral_data : numpy array
        The spectral data matching the conditions.
    """
    matching_rows = lookup_table[
        (lookup_table["Temperature (K)"] == temperature) &
        (lookup_table["Mole Fraction"] == mole_fraction)
    ]

    if matching_rows.empty:
        raise ValueError(f"No matching data for T={temperature}, mole_fraction={mole_fraction}.")

    # Interpolate data for the provided w
